version: '3.4'

services:
  fullstackassignment:
    image: fullstackassignment
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8088:8088
    networks:
      - djangonet
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    env_file: .env-local
     
  database_default:
    # Select one of the following db configurations for the database
    image: postgres:13.5-alpine
    ports:
      - "5432:5432/tcp"  # allow your local dev env to connect to the db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"

    networks:
      - djangonet

    volumes:
      - ".:/app:rw"

networks:
  djangonet: