version: '3.7'

services:
  apidb:
    # Select one of the following db configurations for the database
    image: postgres:12.11
    ports:
      - "5432:5432"  # allow your local dev env to connect to the db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpass"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
      
    networks:
      - djangonet

    volumes:
      - "./app:/app:rw"

  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile_debug
    # command: python manage.py runserver 0.0.0.0:8088
    # command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8088 --nothreading --noreload"]
    # command: ["sh", "-c", "/usr/local/bin/python manage.py runserver 0.0.0.0:8088 && sleep 1000 && cd /app/frontend && npm start"]
    ports:
      - 8088:8088
      # - 5678:5678
      # - 3008:3000
    depends_on:
      - apidb
    links:
      - apidb:apidb
    networks:
      - djangonet
    volumes:
      - "./app:/app:rw"
      - "./data:/data:rw"
    env_file: .env-local

  nodejs:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile_nodejs
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - djangonet
    # volumes:
    #   - "./frontend:/usr/src/app:rw"
    #   - "./data:/data:rw"



  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: chensihai@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - djangonet

  redis:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass 'redis_password' --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - djangonet
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


networks:
  djangonet:
    driver: bridge