version: '3.4'

services:
  apidb:
    # Select one of the following db configurations for the database
    image: postgres:13.5-alpine
    ports:
      - "5432:5432/tcp"  # allow your local dev env to connect to the db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpass"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
      
    networks:
      - djangonet

    volumes:
      - "./app:/app:rw"

  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile_debug
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8088 --nothreading --noreload"]
    ports:
      - 8088:8088
      - 5678:5678
    depends_on:
      - apidb
    links:
      - apidb:apidb
    networks:
      - djangonet
    volumes:
      - "./app:/app:rw"
      - "./data:/data:rw"
    env_file: .env-local

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: chensihai@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - djangonet

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass 'redis_password' --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - djangonet
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


networks:
  djangonet:
    driver: bridge