# Generated by Django 4.0 on 2022-07-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('lattitude', models.CharField(blank=True, max_length=255, verbose_name='Lattitude')),
                ('longtitude', models.CharField(blank=True, max_length=255, verbose_name='Longtitude')),
            ],
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
