# Generated by Django 4.0 on 2022-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='lattitude',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lattitude'),
        ),
        migrations.AddField(
            model_name='people',
            name='longtitude',
            field=models.CharField(blank=True, max_length=255, verbose_name='Longtitude'),
        ),
    ]
