# Generated by Django 4.0 on 2022-07-21 15:04
import os

from django.db import connection, migrations

def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), '/data/', filename)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)
    return    

def initial_data():
    load_data_from_sql('people.sql')
# migrate_data = lambda: load_data_from_sql('migrate_data.sql')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]
